import { useLanguage } from '../i18n/LanguageContext';
import { useEffect, useState } from 'react';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import { PiArrowUpRightBold as ArrowUpRight, PiMagnifyingGlassBold as Search, PiPlusBold as Plus, PiMinusBold as Minus } from 'react-icons/pi';
import { products, productPath, faqs, steps, disclaimer, needs, type Group } from './siteData';
import EnquiryForm from './EnquiryForm';

function PageIntro({label,title,description}:{label:string;title:string;description:string}) {
 const { t } = useLanguage();
 useEffect(()=>{
 document.title=`${t(title)} | ${t('Beemalink Nepal')}`;
 document.querySelector('meta[name="description"]')?.setAttribute('content',t(description));
 },[title,description,t]);
 return <section className="page-intro"><div className="site-container"><nav className="breadcrumb" aria-label={t("Breadcrumb")}><Link to="/">{t("Home")}</Link><span>/</span><span>{t(label)}</span></nav><p className="eyebrow">{t(label)}</p><h1>{t(title)}</h1><p className="page-description">{t(description)}</p></div></section>;
}
const categoryCopy={
 Personal:['Insurance for you and your family.','Explore insurance options for your everyday journeys, health, home and the people you care about.','Get a Personal Insurance Quote'],
 Business:['Protect your business from the unexpected.','Explore protection for your buildings, people, equipment, cargo, vehicles and business operations.','Request Business Insurance Consultation'],
 Agriculture:['Protecting agriculture & livelihoods.','Explore available insurance for eligible crops, livestock and agricultural assets, with guidance for your requirements.','Explore Agriculture Insurance'],
};
function ProductList({items}:{items:typeof products}) {
 const { t } = useLanguage();return <div className="portfolio-list">{items.map(product=><Link key={productPath(product)} to={productPath(product)}><span>{t(product.name)}</span><span className="product-group">{t(product.group)}</span><ArrowUpRight size={17}/></Link>)}</div>;}
export function CategoryPage({group}:{group:Group}) {
 const { t } = useLanguage();
 const [title,description,cta]=categoryCopy[group];
 return <><PageIntro label={`${group} insurance`} title={title} description={description}/><section className="site-container section-space"><div className="section-heading"><h2>{t("Find your starting point.")}</h2><p>{t("Choose a type of insurance to understand the next steps.")}</p></div><ProductList items={products.filter(p=>p.group===group)}/><div className="page-actions"><Link className="button" to={`/get-a-quote?type=${group}`}>{t(cta)}<ArrowUpRight size={18}/></Link><a className="text-link" href="tel:+9779768567022">{t("Talk to an Advisor")}</a></div><p className="coverage-note">{t("Availability, eligibility and policy terms depend on the relevant insurer. We help you understand your options before deciding.")}</p></section></>;
}
export function PortfolioPage() {
 const { t } = useLanguage();
 const [group,setGroup]=useState<Group|'All'>('All'); const [query,setQuery]=useState('');
 const filtered=products.filter(p=>(group==='All'||p.group===group)&&`${p.name} ${p.description} ${t(p.name)} ${t(p.description)}`.toLowerCase().includes(query.toLowerCase()));
 return <><PageIntro label="Insurance portfolio" title="One place. More possibilities." description="Explore personal, business and agriculture insurance. Find a starting point, then let’s work through the details together."/><section className="site-container section-space"><div className="portfolio-tools"><div className="filter-buttons" aria-label={t("Filter insurance products")}>{(['All','Personal','Business','Agriculture'] as const).map(item=><button key={item} className={item===group?'active':''} aria-pressed={item===group} onClick={()=>setGroup(item)}>{t(item)}</button>)}</div><label className="search-field"><Search size={18}/><span className="sr-only">{t("Search insurance products")}</span><input type="search" placeholder={t("Find an insurance product")} value={query} onChange={e=>setQuery(e.target.value)}/></label></div><p className="coverage-note" role="status">{t(filtered.length)}{t(" insurance options")}</p><ProductList items={filtered}/>{!filtered.length&&<p className="no-results">{t("No matching products. ")}<button onClick={()=>{setQuery('');setGroup('All');}}>{t("Show all products")}</button></p>}</section></>;
}
export function ProductPage() {
 const { t } = useLanguage();
 const {slug}=useParams(); const product=products.find(p=>productPath(p)===`/insurance/${slug}`);
 if(!product) return <NotFoundPage/>;
 return <><PageIntro label={`${product.group} insurance`} title={`${product.name} insurance`} description={product.description}/><section className="site-container section-space detail-layout"><div className="prose"><Link className="text-link" to={`/${product.group.toLowerCase()}`}>{t("← All ")}{t(product.group.toLowerCase())}{t(" insurance")}</Link><h2>{t("Start with what matters to you.")}</h2><p>{t(product.description)}{t(" Beemalink helps you clarify your requirements, explore available options and coordinate with the relevant insurance provider.")}</p><h3>{t("Who is it for?")}</h3><p>{t(product.group==='Personal'?'Individuals and families exploring personal insurance requirements.':product.group==='Business'?'Businesses looking to discuss the risks involved in their assets, people or operations.':'Farmers and agricultural businesses exploring protection for eligible agricultural risks.')}{t(" Suitability depends on your circumstances and insurer eligibility requirements.")}</p><h3>{t("Understand the cover before deciding.")}</h3><p>{t("Ask about the insured risks, limits, excess, exclusions and any waiting periods or conditions that apply. Coverage and premiums vary by insurer and policy; review the quotation and policy wording before you choose.")}</p><h3>{t("Documents and next steps.")}</h3><p>{t("Start by telling us who or what you want to insure and the protection you need. We can help identify the relevant information and document checklist for your selected insurance provider.")}</p><h3>{t("Support beyond your policy.")}</h3><p>{t("Need help later? Visit ")}<Link to="/claims">{t("claims assistance")}</Link>{t(" or ")}<Link to="/renewals">{t("renewal support")}</Link>{t(" for guidance and coordination.")}</p></div><aside className="page-panel"><p className="eyebrow">{t("LET’S TALK IT THROUGH")}</p><h2>{t("Your next step.")}</h2><p>{t("Share your requirement and get help understanding the available options.")}</p><Link className="button" to={`/get-a-quote?type=${encodeURIComponent(product.name)}`}>{t("Get a Quote")}<ArrowUpRight size={18}/></Link><a className="text-link" href="tel:+9779768567022">+977 9768567022</a><p className="coverage-note">{t(disclaimer)}</p></aside></section></>;
}
export function SupportPage({type}:{type:'claim'|'renewal'}) {
 const { t } = useLanguage();
 const claim=type==='claim';
 const points=claim?[
 ['Tell us what happened','Notify your insurer as soon as reasonably possible, following your policy requirements. Contact us for help with the process.'],
 ['Identify the documents','We help you understand the information and documents requested by your insurer.'],
 ['Coordinate submission','Get assistance coordinating your claim information with the relevant insurance company.'],
 ['Stay in touch','We can assist with communication and follow-up during the process.'],
 ['The insurer assesses the claim','Assessment and settlement decisions remain with the insurer under the policy terms.'],
 ]:[['Review your expiry date','Ask about expiry tracking and reminders where applicable.'],['Update your information','Share changes to your circumstances or insurance requirements.'],['Explore renewal quotations','Get support coordinating available renewal quotations.'],['Review the details','Understand the updated terms, cover and premium before deciding.'],['Prepare the paperwork','Get help identifying the required renewal documents.'],['Coordinate with your insurer','Receive support with communication and renewal arrangements.']];
 return <><PageIntro label={claim?'Claims assistance':'Renewal support'} title={claim?"When something goes wrong, we’re here to help.":"Don’t let your insurance expire."} description={claim?'We help you understand the process, prepare information and coordinate with your insurance provider.':'Get help reviewing your current insurance and coordinating the next policy period.'}/><section className="site-container section-space detail-layout"><div><h2>{t(claim?'A clearer path forward.':'Keep your protection going.')}</h2><ol className="support-steps">{points.map(([title,copy],i)=><li key={title}><span>0{i+1}</span><div><h3>{t(title)}</h3><p>{t(copy)}</p></div></li>)}</ol><p className="coverage-note">{t(claim?'Claims are assessed and settled by the relevant insurance company according to policy terms, conditions, exclusions and applicable regulations. Beemalink does not make the insurer’s claim decision.':'Sending a renewal enquiry does not renew your policy. Confirm the renewal and effective cover dates with your insurer.')}</p></div><aside className="page-panel"><h2>{t(claim?'Request claims assistance.':'Request renewal support.')}</h2><p>{t("A few details will help us understand your request.")}</p><EnquiryForm type={type}/></aside></section></>;
}
export function AboutPage() {
 const { t } = useLanguage();return <><PageIntro label="About Beemalink" title="Making insurance simple, accessible & understandable." description="Beemalink Nepal brings guidance and coordination to your insurance journey, from your first question to ongoing support."/><section className="site-container section-space prose"><h2>{t("A team to turn to.")}</h2><p>{t("Our purpose is to make insurance easier to understand, access and manage. We help individuals, families and businesses explore suitable options from relevant licensed insurance providers.")}</p><h3>{t("Understand first. Decide with confidence.")}</h3><p>{t("We take the time to understand your requirements and help you review the details before making a choice. Our role includes coordinating documentation, policy arrangements, renewals and claims assistance.")}</p><h3>{t("Our role")}</h3><p>{t(disclaimer)}</p><Link className="text-link" to="/contact">{t("Get in touch ")}<ArrowUpRight size={18}/></Link></section><section className="journey-section section-space"><div className="site-container"><h2>{t("Our approach, step by step.")}</h2><div className="steps-grid">{steps.map(([title,text],i)=><article key={title}><span className="step-number">0{i+1}</span><h3>{t(title)}</h3><p>{t(text)}</p></article>)}</div></div></section></>;}
export function ContactPage() {
 const { t } = useLanguage();return <><PageIntro label="Contact" title="Let’s talk about your insurance needs." description="Whether you’re starting with a question or already have a policy, our team can help you find the next step."/><section className="site-container section-space detail-layout"><div className="prose"><h2>{t("Contact Beemalink.")}</h2><h3>{t("Call us")}</h3><p><a href="tel:+9779768567022">+977 9768567022</a></p><h3>{t("Email us")}</h3><p><a href="mailto:beemalinknepal@gmail.com">{t("beemalinknepal@gmail.com")}</a></p><h3>{t("Find us")}</h3><p>{t("Baneshwor-31, Kathmandu, Nepal")}</p><h3>{t("Office hours")}</h3><p>6:00–18:00</p></div><aside className="page-panel"><h2>{t("What can we help with?")}</h2><p>{t("Choose the right starting point for your enquiry.")}</p><div className="contact-links">{[['Get an insurance quote','/get-a-quote'],['Claims assistance','/claims'],['Renewal support','/renewals']].map(([label,to])=><Link className="text-link" key={to} to={to}>{t(label)}<ArrowUpRight size={18}/></Link>)}<a className="text-link" href="mailto:beemalinknepal@gmail.com">{t("Send a general enquiry")}<ArrowUpRight size={18}/></a></div></aside></section></>;}
export function QuotePage() {
 const { t } = useLanguage();
 const [params]=useSearchParams(); const requested=params.get('type')||'Vehicle'; const valid=['Personal',...needs.map(n=>n.name),...products.map(p=>p.name)]; const initial=valid.includes(requested)?requested:'Vehicle';
 return <><PageIntro label="Get a quote" title="Let’s start with your requirement." description="Tell us what you need to protect. We’ll help you explore available insurance options and understand the next steps."/><section className="site-container section-space detail-layout"><div className="prose"><h2>{t("A conversation, not a commitment.")}</h2><p>{t("Share a few details to get started. Any quotation, cover and premium will depend on the relevant insurer and policy.")}</p><p>{t("Prefer to speak with someone? Call ")}<a href="tel:+9779768567022">+977 9768567022</a>.</p></div><div className="page-panel"><EnquiryForm key={initial} initial={initial}/></div></section></>;
}
export function FaqPage(){
 const { t } = useLanguage();return <><PageIntro label="Frequently asked questions" title="Good questions. Clear answers." description="A little clarity for your insurance journey."/><section className="site-container section-space faq-list">{faqs.map(([q,a])=><details key={q}><summary>{t(q)}<Plus size={18} className="faq-plus"/><Minus size={18} className="faq-minus"/></summary><p>{t(a)}</p></details>)}</section></>;}
export function DisclaimerPage(){
 const { t } = useLanguage();return <><PageIntro label="Our role & disclaimer" title="Your guide. Your coordinator." description={disclaimer}/><section className="site-container section-space prose"><h2>{t("Understanding our role.")}</h2><p>{t("We help you understand your requirements, review available options and coordinate documentation. We do not underwrite risk, set insurer premiums, issue policies ourselves or guarantee claim approval.")}</p><Link className="text-link" to="/contact">{t("Contact us with a question")}<ArrowUpRight size={18}/></Link></section></>;}
export function NotFoundPage(){
 const { t } = useLanguage();return <><PageIntro label="Page not found" title="Let’s find your way." description="This page could not be found. Explore the insurance portfolio or return to the homepage."/><div className="site-container section-space page-actions"><Link className="button" to="/">{t("Return home")}</Link><Link className="text-link" to="/portfolio">{t("Explore insurance")}<ArrowUpRight size={18}/></Link></div></>;}
